<a href="https://colab.research.google.com/github/Sakshithreddy2004/LMS/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr)
#print(arr[1,2])
#print(arr[0,2,2])
print(arr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
6


In [ ]:
import numpy as np
arr= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print('5th element on 2nd row: ',arr[1,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5th element on 2nd row:  10


In [ ]:
#indexing with the help of rows and columns
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print('5th element on 2nd row: ',arr[1,3])
print('3rd element on 1st row: ',arr[0,3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5th element on 2nd row:  9
3rd element on 1st row:  4


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:7])

[2]


In [ ]:
#indexing the elements
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr1)
print(arr1[0:1, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[2 3 4]]


In [ ]:
import numpy as np
array = np.arange(40).reshape(4,10)
print(array)
print()

arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print()

arr=np.array([[[1,2,3],[4,5,6],[1,2,3],[4,5,6]]])
print(arr)
print(arr[1:2,2:3])



[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]

[[1 2 3]
 [4 5 6]]

[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]
[]


In [ ]:
#Adding the elements with the indexing

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,23])
print(arr[3] + arr[9])

#Indexing the array by using step size
print(arr[1:12:3])

14
[ 2  5  8 11]
