<a href="https://colab.research.google.com/github/Sakshithreddy2004/LMS/blob/main/panda_dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
import pandas as pd

#upload local files
uploaded=files.upload()

#get filename
aaa=list(uploaded.keys())[0]

#read csv file using pandas
df=pd.read_csv(aaa)
df.head(10)

Saving customers-100.csv to customers-100 (1).csv


Index      Customer Id First Name  Last Name  \
0      1  DD37Cf93aecA6Dc     Sheryl     Baxter   
1      2  1Ef7b82A4CAAD10    Preston     Lozano   
2      3  6F94879bDAfE5a6        Roy      Berry   
3      4  5Cef8BFA16c5e3c      Linda      Olsen   
4      5  053d585Ab6b3159     Joanna     Bender   
5      6  2d08FB17EE273F4      Aimee      Downs   
6      7  EA4d384DfDbBf77     Darren       Peck   
7      8  0e04AFde9f225dE      Brett     Mullen   
8      9  C2dE4dEEc489ae0     Sheryl     Meyers   
9     10  8C2811a503C7c5a   Michelle  Gallagher   

                           Company               City  \
0                  Rasmussen Group       East Leonard   
1                      Vega-Gentry  East Jimmychester   
2                    Murillo-Perry      Isabelborough   
3  Dominguez, Mcmillan and Donovan         Bensonview   
4         Martin, Lang and Andrade     West Priscilla   
5                     Steele Group      Chavezborough   
6     Lester, Woodard and Mitchell           Lake Ana   
7     Sanford, Davenport and Giles            Kimport   
8                   Browning-Simon       Robersonstad   
9                     Beck-Hendrix         Elaineberg   

                      Country                 Phone 1                Phone 2  \
0                       Chile            229.077.5154       397.884.0519x718   
1                    Djibouti              5153435776       686-620-1820x944   
2         Antigua and Barbuda         +1-539-402-0259    (496)978-3969x58947   
3          Dominican Republic  001-808-617-6467x12895        +1-813-324-8756   
4  Slovakia (Slovak Republic)  001-234-203-0635x76146  001-199-446-3860x3486   
5      Bosnia and Herzegovina     (283)437-3886x88321           999-728-1637   
6            Pitcairn Islands      (496)452-6181x3291   +1-247-266-0963x4995   
7                    Bulgaria    001-583-352-7197x297       001-333-145-0369   
8                      Cyprus       854-138-4911x5772    +1-448-910-2276x729   
9                 Timor-Leste        739.218.2516x459   001-054-401-0347x617   

                         Email Subscription Date                      Website  
0     zunigavanessa@smith.info        2020-08-24   http://www.stephenson.com/  
1              vmata@colon.com        2021-04-23        http://www.hobbs.com/  
2          beckycarr@hogan.com        2020-03-25     http://www.lawrence.com/  
3  stanleyblackwell@benson.org        2020-06-02   http://www.good-lyons.com/  
4      colinalvarado@miles.net        2021-04-17  https://goodwin-ingram.com/  
5          louis27@gilbert.com        2020-02-25       http://www.berger.net/  
6          tgates@cantrell.com        2021-08-24          https://www.le.com/  
7              asnow@colon.com        2021-04-12  https://hammond-ramsey.com/  
8      mariokhan@ryan-pope.org        2020-01-13     https://www.bullock.net/  
9            mdyer@escobar.net        2021-11-08           https://arias.com/

In [ ]:
df.tail(15)

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
530  2240000  1950         3          1        1       no        no       no   
531  2233000  5300         3          1        1       no        no       no   
532  2135000  3000         2          1        1       no        no       no   
533  2100000  2400         3          1        2      yes        no       no   
534  2100000  3000         4          1        2      yes        no       no   
535  2100000  3360         2          1        1      yes        no       no   
536  1960000  3420         5          1        2       no        no       no   
537  1890000  1700         3          1        2      yes        no       no   
538  1890000  3649         2          1        1      yes        no       no   
539  1855000  2990         2          1        1       no        no       no   
540  1820000  3000         2          1        1      yes        no      yes   
541  1767150  2400         3          1        1       no        no       no   
542  1750000  3620         2          1        1      yes        no       no   
543  1750000  2910         3          1        1       no        no       no   
544  1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
530             yes              no        0       no      unfurnished  
531              no             yes        0      yes      unfurnished  
532              no              no        0       no      unfurnished  
533              no              no        0       no      unfurnished  
534              no              no        0       no      unfurnished  
535              no              no        1       no      unfurnished  
536              no              no        0       no      unfurnished  
537              no              no        0       no      unfurnished  
538              no              no        0       no      unfurnished  
539              no              no        1       no      unfurnished  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished

In [ ]:
df.iloc[[1,3,6,23]]

#selective finding the rows for 1st , 3rd, 6th, 23rd

Index      Customer Id First Name   Last Name  \
1       2  1Ef7b82A4CAAD10    Preston      Lozano   
3       4  5Cef8BFA16c5e3c      Linda       Olsen   
6       7  EA4d384DfDbBf77     Darren        Peck   
23     24  010468dAA11382c      Janet  Valenzuela   

                            Company               City  \
1                       Vega-Gentry  East Jimmychester   
3   Dominguez, Mcmillan and Donovan         Bensonview   
6      Lester, Woodard and Mitchell           Lake Ana   
23                  Watts-Donaldson      Veronicamouth   

                             Country                 Phone 1  \
1                           Djibouti              5153435776   
3                 Dominican Republic  001-808-617-6467x12895   
6                   Pitcairn Islands      (496)452-6181x3291   
23  Lao People's Democratic Republic       354.259.5062x7538   

                 Phone 2                        Email Subscription Date  \
1       686-620-1820x944              vmata@colon.com        2021-04-23   
3        +1-813-324-8756  stanleyblackwell@benson.org        2020-06-02   
6   +1-247-266-0963x4995          tgates@cantrell.com        2021-08-24   
23          500.433.2022        stefanie71@spence.com        2020-09-08   

                       Website  
1        http://www.hobbs.com/  
3   http://www.good-lyons.com/  
6          https://www.le.com/  
23         https://moreno.biz/

In [ ]:
df.loc[[1,6]]

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
1  12250000  8960         4          4        4      yes        no       no   
6  10150000  8580         4          3        4      yes        no       no   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
1              no             yes        3       no        furnished  
6              no             yes        2      yes   semi-furnished

In [ ]:
#retreaving the rows and column
df.iloc[1:15,2:4]


bedrooms  bathrooms
1          4          4
2          3          2
3          4          2
4          4          1
5          3          3
6          4          3
7          5          3
8          4          1
9          3          2
10         3          1
11         4          3
12         4          2
13         4          2
14         3          2

In [ ]:
#filter the data frames with rows and columns by using iloc rows starting from 5 to 60 and column should be company,city and country

from google.colab import files
import pandas as pd

uploaded=files.upload()

aaa=list(uploaded.keys())[0]

#read csv file using pandas
df=pd.read_csv(aaa)
df.iloc[5:10,4:7]


Saving customers-100.csv to customers-100 (3).csv


Company           City                 Country
5                  Steele Group  Chavezborough  Bosnia and Herzegovina
6  Lester, Woodard and Mitchell       Lake Ana        Pitcairn Islands
7  Sanford, Davenport and Giles        Kimport                Bulgaria
8                Browning-Simon   Robersonstad                  Cyprus
9                  Beck-Hendrix     Elaineberg             Timor-Leste

In [ ]:
df.iloc[5:9,5:7]

City                 Country
5  Chavezborough  Bosnia and Herzegovina
6       Lake Ana        Pitcairn Islands
7        Kimport                Bulgaria
8   Robersonstad                  Cyprus

In [ ]:
df.describe()

Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [ ]:
df.iloc[3,2:5]

First Name                              Linda
Last Name                               Olsen
Company       Dominguez, Mcmillan and Donovan
Name: 3, dtype: object

In [ ]:
display(dtat.loc[(data.Brand =='Maruti')])

NameError: name 'df' is not defined

In [ ]:
df.head(10)
df.iloc[1:50,1:5]
data=df['First Name'] == 'Preston'
data

0     False
1      True
2     False
3     False
4     False
      ...  
95    False
96    False
97    False
98    False
99    False
Name: First Name, Length: 100, dtype: bool

In [ ]:
df.drop('Phone 2',axis =1)

Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter   
1       2  1Ef7b82A4CAAD10    Preston    Lozano   
2       3  6F94879bDAfE5a6        Roy     Berry   
3       4  5Cef8BFA16c5e3c      Linda     Olsen   
4       5  053d585Ab6b3159     Joanna    Bender   
..    ...              ...        ...       ...   
95     96  cb8E23e48d22Eae       Karl     Greer   
96     97  CeD220bdAaCfaDf       Lynn  Atkinson   
97     98  28CDbC0dFe4b1Db       Fred    Guerra   
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer   
99    100  2354a0E336A91A1   Clarence    Haynes   

                            Company               City  \
0                   Rasmussen Group       East Leonard   
1                       Vega-Gentry  East Jimmychester   
2                     Murillo-Perry      Isabelborough   
3   Dominguez, Mcmillan and Donovan         Bensonview   
4          Martin, Lang and Andrade     West Priscilla   
..                              ...                ...   
95                        Carey LLC       East Richard   
96            Ware, Burns and Oneal       New Bradview   
97                    Schmitt-Jones         Ortegaland   
98               Fitzgerald-Harrell    Lake Elijahview   
99               Le, Nash and Cross          Judymouth   

                       Country                 Phone 1  \
0                        Chile            229.077.5154   
1                     Djibouti              5153435776   
2          Antigua and Barbuda         +1-539-402-0259   
3           Dominican Republic  001-808-617-6467x12895   
4   Slovakia (Slovak Republic)  001-234-203-0635x76146   
..                         ...                     ...   
95                      Guyana     (188)169-1674x58692   
96                   Sri Lanka         +1-846-706-2218   
97             Solomon Islands    +1-753-067-8419x7170   
98                       Aruba           (530)311-9786   
99                    Honduras           (753)813-6941   

                             Email Subscription Date  \
0         zunigavanessa@smith.info        2020-08-24   
1                  vmata@colon.com        2021-04-23   
2              beckycarr@hogan.com        2020-03-25   
3      stanleyblackwell@benson.org        2020-06-02   
4          colinalvarado@miles.net        2021-04-17   
..                             ...               ...   
95                hhart@jensen.com        2022-01-30   
96               vkemp@ferrell.com        2021-07-10   
97                swagner@kane.org        2021-09-18   
98  mccarthystephen@horn-green.biz        2021-08-11   
99          colleen91@faulkner.biz        2020-03-11   

                              Website  
0          http://www.stephenson.com/  
1               http://www.hobbs.com/  
2            http://www.lawrence.com/  
3          http://www.good-lyons.com/  
4         https://goodwin-ingram.com/  
..                                ...  
95            http://hayes-perez.com/  
96         https://novak-allison.com/  
97              https://www.ross.com/  
98               http://watkins.info/  
99  http://www.hatfield-saunders.net/  

[100 rows x 11 columns]

In [ ]:
df.isnull()

Index  Customer Id  First Name  Last Name  Company   City  Country  \
0   False        False       False      False    False  False    False   
1   False        False       False      False    False  False    False   
2   False        False       False      False    False  False    False   
3   False        False       False      False    False  False    False   
4   False        False       False      False    False  False    False   
..    ...          ...         ...        ...      ...    ...      ...   
95  False        False       False      False    False  False    False   
96  False        False       False      False    False  False    False   
97  False        False       False      False    False  False    False   
98  False        False       False      False    False  False    False   
99  False        False       False      False    False  False    False   

    Phone 1  Phone 2  Email  Subscription Date  Website  
0     False    False  False              False    False  
1     False    False  False              False    False  
2     False    False  False              False    False  
3     False    False  False              False    False  
4     False    False  False              False    False  
..      ...      ...    ...                ...      ...  
95    False    False  False              False    False  
96    False    False  False              False    False  
97    False    False  False              False    False  
98    False    False  False              False    False  
99    False    False  False              False    False  

[100 rows x 12 columns]

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Subscription Date']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Subscription Date'}, axis=1)
              .sort_values('Subscription Date', ascending=True))
  xs = counted['Subscription Date']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_0.sort_values('Subscription Date', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Subscription Date')
_ = plt.ylabel('count()')

In [ ]:
#import the module
import pandas as pd

# Creating a sample dataframe

data = pd.DataFrame({'Brand':['Maruti,'Hyundai','Tata','Mahindra','Maruti','Hyundai',
'Renault','Tata','Maruti'],
  'Year':[2012,2014,2011,2015,2012,2016,2014,2018,2019]})

In [ ]:
display(data.loc[(data.Brand == 'Maruti')])


AttributeError: 'Series' object has no attribute 'Brand'

In [ ]:
data.Mileage < 25

AttributeError: 'Series' object has no attribute 'Mileage'

In [ ]:
import numpy as np
arr= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print('5th element on 2nd row: ',arr[1,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5th element on 2nd row:  10


In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr)
#print(arr[1,2])
#print(arr[0,2,2])
print(arr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
6


In [ ]:
#sample d
import pandas as pd

data = {
    'Transaction_ID': [1,2,3,4,5],
    'Product_ID': [101,102,103,101,104],
    'Product_Name': ['shirt','pants','shoes','Hat','shirt'],
    'Customer_ID': [201,202,203,201,204],
    'Quantity': [2,3,1,1,2],
    'Price_Per_Unit': [30,40,50,30,15],
}
customer_data = {
    'CustomerID': [101,102,103,104],
    'CustomerName': ['Alice','Bob','Charlie','David'],
    'Age': [30,35,40,25],
    'City': ['New York','Los Angeles','Chicago','Huston'],

}

#convert data into Dataframe
sales_df = pd.DataFrame(data)
customers_df = pd.DataFrame(customer_data)

print("Sales DataFrame:")
print(sales_df.head())

# 1. Exploring the dataset using shape and describe

print("\nShape of sales data:", sales_df.shape)
print("\nDescription of sales data:")
print(sales_df.describe())
print("Sales dataframe",sales_df)
print("\nCustomers dataframe:\n",customers_df)

Sales DataFrame:
   Transaction_ID  Product_ID Product_Name  Customer_ID  Quantity  \
0               1         101        shirt          201         2   
1               2         102        pants          202         3   
2               3         103        shoes          203         1   
3               4         101          Hat          201         1   
4               5         104        shirt          204         2   

   Price_Per_Unit  
0              30  
1              40  
2              50  
3              30  
4              15  

Shape of sales data: (5, 6)

Description of sales data:
       Transaction_ID  Product_ID  Customer_ID  Quantity  Price_Per_Unit
count        5.000000     5.00000      5.00000   5.00000        5.000000
mean         3.000000   102.20000    202.20000   1.80000       33.000000
std          1.581139     1.30384      1.30384   0.83666       13.038405
min          1.000000   101.00000    201.00000   1.00000       15.000000
25%          2.000000   10

In [ ]:
# fiter a dataframe of sales dataframe where sales amount >400
display(data.loc[(data.sales_amount > 400)])

AttributeError: 'dict' object has no attribute 'loc'